# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(verbose_name='Season')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('is_winner', models.BooleanField(verbose_name='Winner')),
                ('confidence', models.IntegerField(verbose_name='Confidence Ranking')),
            ],
        ),
        migrations.CreateModel(
            name='NflGame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(verbose_name='Season')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('game_date', models.DateField(verbose_name='Game Date')),
                ('game_time', models.DateTimeField(verbose_name='Game Time')),
                ('home_team_score', models.IntegerField(verbose_name='Home Team Score')),
                ('away_team_score', models.IntegerField(verbose_name='Away Team Score')),
                ('is_final', models.BooleanField(verbose_name='Game Complete')),
            ],
        ),
        migrations.CreateModel(
            name='NflTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Team Name')),
                ('city', models.CharField(max_length=30, verbose_name='Team City')),
                ('short_name', models.CharField(max_length=3, verbose_name='Team Short Name')),
                ('wins', models.IntegerField(verbose_name='Wins')),
                ('losses', models.IntegerField(verbose_name='Losses')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('wins', models.IntegerField(verbose_name='Wins')),
                ('losses', models.IntegerField(verbose_name='Losses')),
            ],
        ),
        migrations.AddField(
            model_name='nflgame',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.NflTeam', verbose_name='Away Team'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.NflTeam', verbose_name='Home Team'),
        ),
        migrations.AddField(
            model_name='nflgame',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.NflTeam', verbose_name='Winning Team'),
        ),
        migrations.AddField(
            model_name='entry',
            name='nfl_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.NflGame', verbose_name='NFL Game'),
        ),
        migrations.AddField(
            model_name='entry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.Player', verbose_name='Player Entry'),
        ),
    ]
