# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0004_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='projected_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.NflTeam', verbose_name='Projected Winner'),
        ),
    ]
