# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0005_entry_projected_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Entry Complete'),
        ),
        migrations.AddField(
            model_name='entry',
            name='points_earned',
            field=models.IntegerField(default=0, verbose_name='Points Earned'),
        ),
        migrations.AddField(
            model_name='entry',
            name='potential_points',
            field=models.IntegerField(default=0, verbose_name='Potential Points'),
        ),
    ]
