# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0013_player_active_wk_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.IntegerField(verbose_name='Season')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('is_active', models.BooleanField(verbose_name='Active Flag')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.Player', verbose_name='Player Entry')),
            ],
        ),
    ]
