# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0014_playerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflteam',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Team Alias'),
        ),
    ]
