# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0016_auto_20171209_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerentry',
            name='points_earned',
            field=models.IntegerField(default=0, null=True, verbose_name='Points Earned'),
        ),
        migrations.AddField(
            model_name='playerentry',
            name='points_lost',
            field=models.IntegerField(default=0, null=True, verbose_name='Points Lost'),
        ),
    ]
