# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0017_auto_20171210_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerentry',
            name='nfl_games_lost',
            field=models.IntegerField(default=0, null=True, verbose_name='NFL Games Lost'),
        ),
        migrations.AddField(
            model_name='playerentry',
            name='nfl_games_won',
            field=models.IntegerField(default=0, null=True, verbose_name='NFL Games Won'),
        ),
    ]
