# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0018_auto_20171210_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repeat_nfl_score_update_id', models.CharField(max_length=255, verbose_name='task id for repeat_nfl_score')),
            ],
        ),
    ]
