# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0020_auto_20171226_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_access',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last site access time'),
        ),
    ]
