# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflgame',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='confidence.NflTeam', verbose_name='Winning Team'),
        ),
    ]
