# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0002_auto_20171118_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='pick_selection',
            field=models.IntegerField(blank=True, choices=[(1, 'Home Team'), (2, 'Away Team')], null=True, verbose_name='Pick'),
        ),
    ]
