# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0003_entry_pick_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name'),
        ),
    ]
