# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidence', '0007_auto_20171125_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_current_entry',
            field=models.BooleanField(default=False, verbose_name='Has Current Entry?'),
        ),
    ]
